services:
  - type: web
    name: telegram-bot
    env: php
    plan: free
    branch: main
    rootDir: .
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: BOT_TOKEN
        sync: false # 手動在 Render 儀表板設置
